container:
  image: circleci/node:10-browsers
  cpu: 8
  memory: 24

check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  config_script: cp config/ci.config.json config/project.json
  build_script: yarn build
  version_script:
    - which firefox
    - firefox -v
    - which google-chrome
    - google-chrome --version
  lsof_script: sudo apt-get install lsof
  test_script: xvfb-run yarn test 